### ISSUE TITLE
Serial console issue for the arndale 5250.

### ISSUE THREAD

**Issue by MazenEzzeddine** [kesl/khypervisor#238]
Dear all,

I am currently trying to run the khypervisor on my arndale 5250, I compiled/built the system exactly using the steps documented on github (for different guests linux, bm, linaro), However, I am not able to see any output on the console. The system hangs at "starting application at : ". In all cases, the code in boot.S for UART seems weird (e.g. ldr r0, = 0x1c090000 which is for the versatile platform). 

Could you please route me to a more recent/updated version of the code and the documentation. Please help me by pointing me to a reliable document on how to run the khypervisor on the arndale 5250. 

Also what EXACT patches are required for u-boot, linux kernel, linaro kernel when running the khypervisor on the arndale? I am applying the patches explicitly.

Thank you so much and best regards.﻿

**Comment by Wonseok** [comment]
Hi MazenEzzeddine,

I guess that the issue is related branch problem. "v1-dev" is work-in-progress, so I suggest that you can use "v1" branch than v1-dev. Make sure to solve the issues, let me know your branch name and commit version.

Thanks,
Wonseok.

**Comment by MazenEzzeddine** [comment]
Thank you so much Wonseok, I will do an report the result.

Regards,

**Comment by in1004kyu** [comment]
Hi MazenEzzeddine,

I tested and modified v1-dev branch. Now khypervisor is working at v1-dev. Please refer "Download hypervisor" and "How to test RTOS guest + linux guest" section at "https://github.com/kesl/khypervisor/tree/v1-dev/platform-device/cortex_a15x2_arndale/README.md" file.

Plus, we use insignal's linux that arndale.org's primary distribution version
Commit number is "7d1f9aeff1ee4a20b1aeb377dd0f579fe9647619".
Insignal linux git url : git://git.insignal.co.kr/samsung/exynos/android/kernel/samsung/exynos3.0

Our uboot's repository was missied. So I changed from uboot to linaro's stable uboot.
uboot url : git://git.linaro.org/boot/u-boot-linaro-stable.git

If you see other issue in latest source then I will try to fix it for you.

Regards,
Inkyu

**Comment by in1004kyu** [comment]
Hi MazenEzzeddine,

I tested and modified v1-dev branch. Now khypervisor is working at v1-dev.
Please refer "Download hypervisor" and "How to test RTOS guest + linux
guest" section at "
https://github.com/kesl/khypervisor/tree/v1-dev/platform-device/cortex_a15x2_arndale/README.md"
file.

Plus, we use insignal's linux that arndale.org's primary distribution
version
Commit number is "7d1f9aeff1ee4a20b1aeb377dd0f579fe9647619".
Insignal linux git url : git://
git.insignal.co.kr/samsung/exynos/android/kernel/samsung/exynos3.0

Our uboot's repository was missied. So I changed from old uboot to linaro's
stable uboot.
uboot url : git://git.linaro.org/boot/u-boot-linaro-stable.git

If you see other issue in latest source then I will try to fix it for you.

Regards,
Inkyu

2015-01-23 15:51 GMT+09:00 MazenEzzeddine notifications@github.com:

**Comment by MazenEzzeddine** [comment]
Thank you so much, I will do and report the result.

Many thanks and best regards.

**Comment by MazenEzzeddine** [comment]
Dear,

Yes I can see the hypervisor output. My mistake, I was using a different branch, different u-boot, and applying redudant patches. 
You will hear from many times ;) 
Thank a lot and best regards.

**Comment by Wonseok** [comment]
​Great!
When you need my help, feel free to ask.

Thanks,
Wonseok.

2015-01-24 19:14 GMT+09:00 MazenEzzeddine notifications@github.com:
